### ISSUE TITLE
replace/remove elements

### ISSUE THREAD

**Issue by cfhaak** [bundesverfassung-oesterreich/bv-transkribus-export#20]
- [x] ab -> p (div?)
- [ ] remove lb

**Comment by csae8092** [comment]
Put IT in the Agenda for the next Meeting and let Jörg ET all decide

**Comment by cfhaak** [comment]
that a good idea, will do

**Comment by cfhaak** [comment]
lbs shouldn't be reoved, but hidden in frontend
